version: '3'

includes:
  assets:
    taskfile: ../lawn-assets
    dir: ../lawn-assets
    internal: true

tasks:
  configure:
    # Hack to use Ninja generator to generate compile_commands.json for clangd
    - rm build/CMakeCache.txt
    - >
      cmake --preset=windows-msvc-x64
      -B build -G Ninja
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      -DCMAKE_BUILD_TYPE=Debug
    - rm build/CMakeCache.txt
    # use MSVC to generate the actual configs
    - >
      cmake --preset=windows-msvc-x64
      -B build -G "Visual Studio 18 2026"

  build:
    - task: do-build
      vars:
        CONFIG: Debug
  build-rel:
    - task: do-build
      vars:
        CONFIG: Release

  do-build:
    internal: true
    vars:
      THREADS:
        sh: nproc
    cmds:
      - cmake --build build --config {{.CONFIG}} -- /m:{{.THREADS}}
      - cp lib/bass/bin/bass.dll Export

  build-assets:
    - task: assets:build

  run:
    - cd Export && ./LawnProject.exe

  clean:
    - rm -rf build Export
