version: '3'

includes:
  assets:
    taskfile: ../lawn-assets
    dir: ../lawn-assets
    internal: true

tasks:
  configure:
    cmds:
      - task: configure-clang
      - task: configure-msvc
  configure-clang:
    - >
      cmake --preset=windows-msvc-x64
      -B build -G Ninja
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      -DCMAKE_BUILD_TYPE=Debug
    - rm build/CMakeCache.txt
  configure-msvc:
    - >
      cmake --preset=windows-msvc-x64
      -B build -G "Visual Studio 18 2026"

  build:
    vars:
      NPROC:
        sh: nproc
    cmds:
      - cmake --build build --config Debug -- /m:{{.NPROC}}

  build-release:
    vars:
      NPROC:
        sh: nproc
    cmds:
      - cmake --build build --config Release -- /m:{{.NPROC}}

  build-assets:
    - task: assets:build

  run:
    - cd Export && ./LawnProject.exe

  clean:
    - rm -rf build Export
