version: '3'

includes:
  common:
    taskfile: mono-dev/task/common.yaml
    optional: true
    flatten: true

tasks:
  install:
    - rm -rf mono-dev
    - git clone https://github.com/Pistonight/mono-dev --depth 1


  setup:
    - silent: true
      cmd: >
        if ! [ -e packages/pvz-assets/main-en.pak ]; then
          echo 'please get main.pak from GOTY EN version (1.2.0.1096) and put it in packages/pvz-assets as main-en.pak';
          exit 2;
        fi;
        if ! [ -e packages/pvz-assets/main-zh.pak ]; then
          echo 'please get main.pak from GOTY ZH version (1.2.0.1096) and put it in packages/pvz-assets as main-zh.pak';
          exit 2;
        fi;
    - pvz-bintools pakc --unpack packages/pvz-assets/main-en.pak
    - pvz-bintools pakc --unpack packages/pvz-assets/main-zh.pak
