version: '3'

includes:
  common:
    taskfile: mono-dev/task/common.yaml
    optional: true
    flatten: true

  pvz-pakc:    { taskfile: packages/pvz-pakc,     dir: packages/pvz-pakc,     internal: true }
  pvz-reanimc: { taskfile: packages/pvz-reanimc,  dir: packages/pvz-reanimc,  internal: true }
  pvz-utils:   { taskfile: packages/pvz-utils,    dir: packages/pvz-utils,    internal: true }

tasks:
  install:
    - rm -rf mono-dev
    - git clone https://github.com/Pistonight/mono-dev --depth 1


  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: lisensor

  setup:
    - silent: true
      cmd: >
        if ! [ -e packages/pvz-assets/main.pak ]; then
          echo 'please get main.pak from GOTY EN version (1.2.0.1096) and put it in packages/pvz-assets';
          exit 2;
        fi;
    - cargo run --release --bin pvz-pakc -- --unpack packages/pvz-assets/main.pak


  check:
    - lisensor
    - task: pvz-utils:check
    - task: pvz-pakc:check
    - task: pvz-reanimc:check

  test:
    - task: pvz-reanimc:test
