version: '3'

includes:
  ccpp:
    taskfile: ../../mono-dev/task/ccpp.yaml
    internal: true
    optional: true

tasks:
  check:
    - task: ccpp:fmt-check
      vars:
        SOURCE: src src-mixin
  fix:
    - task: ccpp:fmt-fix
      vars:
        SOURCE: src src-mixin

  fix-srcdrop:
    - task: fix
