version: '3'

includes:
  ccpp:
    taskfile: ../../mono-dev/task/ccpp.yaml
    internal: true
    optional: true

tasks:
  check:
    - task: ccpp:fmt-check
      vars:
        SOURCE: src
  fix:
    - task: ccpp:fmt-fix
      vars:
        SOURCE: src

  fix-srcdrop:
    - task: fix

  build:
    sources:
      - bass/bin/bass.dll
    generates:
      - ../../target/run/bass.dll
    cmds:
      - silent: true
        cmd: |
          mkdir -p ../../target/run
          cp bass/bin/bass.dll ../../target/run/bass.dll;
          echo '==> copied lib dlls';
