import os
from pathlib import Path

from src.util import _common, _fmt
from src.srcdrop import _transformer

def copy_files():
    print(f"{_fmt.GREEN}==> copying framework files{_fmt.RESET}")
    our_root_path = _get_target_project_root()
    framework_path = _common.get_upstream_root()
    framework_src_path = framework_path / "src"
    exclude = set([
        # Main files are part of buildfiles
        framework_src_path / "main.cpp",
        framework_src_path / "main_icon.ico",
        framework_src_path / "LawnProject.rc",
        framework_src_path / "SexyAppFramework" / "resource.h",
        # Resources are generated by us
        framework_src_path / "Resources.cpp",
        framework_src_path / "Resources.h",

        # git-ignored ones
        framework_src_path / "SexyAppFramework" / "BuildInfo.h",
        # mixed-ins (see resod-framework/src-mixin)
        framework_src_path / "SexyAppFramework" / "BuildInfo.h.in",
        framework_src_path / "Lawn" / "ResoddedFramework" / "SettingsDialog.cpp",
        framework_src_path / "Lawn" / "ResoddedFramework" / "SettingsDialog.h",
    ])

    transformers = _get_transformers()
    # these are part of resod-lib
    exclude_dirs = set([
        "ImageLib", "PakLib"
    ])

    target_src_dirpath = our_root_path / "src"
    _common.rm_rf(target_src_dirpath)
    for (dirpath, _, filenames) in os.walk(framework_src_path):
        currdir_name = os.path.basename(dirpath)
        if currdir_name in exclude_dirs:
            continue
        dirpath = Path(dirpath)
        reldirpath = dirpath.relative_to(framework_src_path)

        if dirpath == framework_src_path:
            target_dirpath = target_src_dirpath / "LawnApp"
        else:
            target_dirpath = target_src_dirpath / reldirpath
        target_dirpath.mkdir(parents = True, exist_ok=True)

        for file in filenames:
            if file.endswith("CMakeLists.txt"):
                continue
            if file.endswith(".gitignore"):
                continue
            filepath = dirpath / file
            if filepath in exclude:
                continue
            _transformer.copy_transform(filepath, target_dirpath / file, transformers)

    run_fix()


def transform():
    print(f"{_fmt.GREEN}==> transforming framework files{_fmt.RESET}")
    our_root_path = _get_target_project_root()
    transformers = _get_transformers()
    for (dirpath, _, filenames) in os.walk(our_root_path / "src"):
        for file in filenames:
            if _common.is_src_file(file) or _common.is_header_file(file):
                _transformer.transform(Path(dirpath) / file, transformers)
    run_fix()


def run_fix():
    print(f"{_fmt.CYAN}==> formatting framework files{_fmt.RESET}")
    _transformer.run_fix(_get_target_project_root())


def _get_transformers():
    return [
        _transformer.transform_includes,
        _transformer.transform_lib_includes,
        _transformer.transform_resolve_framework_includes,
    ]


def _get_target_project_root():
    return _common.get_packages_root() / "resod-framework"

