version: '3'

tasks:
  setup-piston:
    - rm -rf ResoddedFramework
    - git clone git@github.com:Pistonight/ResoddedFramework
    - git -C ResoddedFramework remote add upstream https://github.com/LawnProject/ResoddedFramework
    - git -C ResoddedFramework fetch upstream

  setup:
    - rm -rf ResoddedFramework
    - git clone https://github.com/Pistonight/ResoddedFramework

  sync-upstream:
    - git -C ResoddedFramework fetch upstream
    - git -C ResoddedFramework checkout main
    - git -C ResoddedFramework merge upstream/main --ff-only
    - git -C ResoddedFramework push

  open-fork:
    - cmd /c start "" "https://github.com/Pistonight/ResoddedFramework"
  open-upstream:
    - cmd /c start "" "https://github.com/LawnProject/ResoddedFramework"

  build:
    - cd ../build-script && uv run src/main.py upstream build {{.CLI_ARGS}}

  clean:
    - cd ../build-script && uv run src/main.py upstream build clean all

  nuke:
    - task: clean
    - rm -rf ResoddedFramework

  transform:
    - cd ../build-script && uv run src/main.py upstream transform

  upgrade:
    - cd ../build-script && uv run src/main.py upstream upgrade

  merge-upgrade:
    - git checkout {{.CLI_ARGS}}
    - git merge srcdrop_/done --ff-only

  pak:
    - cp ../pvz-assets/main12en.pak ResoddedFramework/Export/main.pak
    - cp -R ../pvz-assets/properties ResoddedFramework/Export

  run:
    - cd ResoddedFramework/Export && ./LawnProject.exe
  devenv:
    - cd ../build-script && uv run src/main.py upstream devenv

  build-run:
    aliases: [br]
    cmds:
      - task: build
      - task: run


