version: '3'

includes:
  ccpp:
    taskfile: ../../mono-dev/task/ccpp.yaml
    internal: true
    optional: true

tasks:
  check:
    - task: ccpp:fmt-check
      vars:
        SOURCE: src src-mixin
  fix:
    - task: ccpp:fmt-fix
      vars:
        SOURCE: src src-mixin

  fix-srcdrop:
    - task: fix

  build:
    - cmd: cd ../build-script && uv run src/main.py lawn build {{.CLI_ARGS}}
      silent: true

  clean:
    - cmd: cd ../build-script && uv run src/main.py lawn build clean all

  devenv:
    - cmd: cd ../build-script && uv run src/main.py lawn devenv
