version: '3'

includes:
  ccpp:
    taskfile: ../../mono-dev/task/ccpp.yaml
    internal: true
    optional: true

tasks:
  check:
    - task: ccpp:fmt-check
      vars:
        SOURCE: src
  fix:
    - task: ccpp:fmt-fix
      vars:
        SOURCE: src

  fix-srcdrop:
    - task: fix

  build:
    - python build.py {{.CLI_ARGS}}

  clean:
    - python build.py clean all
